# Generated by Django 5.0.7 on 2024-08-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galaxies', '0002_galaxy_image_galaxy_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'creature',
                'verbose_name_plural': 'creatures',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hintText', models.TextField(verbose_name='Hint Text')),
            ],
            options={
                'verbose_name': 'hint',
                'verbose_name_plural': 'hints',
            },
        ),
        migrations.CreateModel(
            name='CreatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='creatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='planets.creature')),
            ],
            options={
                'verbose_name': 'creature image',
                'verbose_name_plural': 'creature images',
            },
        ),
        migrations.CreateModel(
            name='HintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imageHints/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='planets.hint')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('planetImage', models.ImageField(upload_to='planets/', verbose_name='Planet Image')),
                ('mapImage', models.ImageField(upload_to='planets/', verbose_name='Map Image')),
                ('galaxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet_galaxy', to='galaxies.galaxy', verbose_name='Galaxy')),
            ],
            options={
                'verbose_name': 'planet',
                'verbose_name_plural': 'planets',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='phases/', verbose_name='Image')),
                ('creatures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planets.creature', verbose_name='Creatures')),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planets.planet', verbose_name='Planet')),
            ],
            options={
                'verbose_name': 'phase',
                'verbose_name_plural': 'phases',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField(verbose_name='Question Text')),
                ('hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planets.hint', verbose_name='Hint Text')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planets.phase', verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativeText', models.TextField(verbose_name='Alternative Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='planets.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'alternative',
                'verbose_name_plural': 'alternatives',
            },
        ),
    ]
