# Generated by Django 5.0.7 on 2024-08-05 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='planets.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phases/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mapImage',
            field=models.ImageField(blank=True, null=True, upload_to='planets/', verbose_name='Map Image'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planetImage',
            field=models.ImageField(blank=True, null=True, upload_to='planets/', verbose_name='Planet Image'),
        ),
        migrations.DeleteModel(
            name='HintImage',
        ),
    ]
