# Generated by Django 5.0.7 on 2024-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_hint_user_alter_alternative_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
    ]
