# Generated by Django 5.0.7 on 2024-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alternative_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creatures/', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='CreatureImage',
        ),
    ]
