# Generated by Django 5.0.7 on 2024-08-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_creature_image_delete_creatureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planets.hint', verbose_name='Hint Text'),
        ),
    ]
