# Generated by Django 5.0.7 on 2024-08-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0006_alter_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
