# Generated by Django 5.0.7 on 2024-07-31 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life', models.IntegerField(default=0, verbose_name='life')),
                ('attack', models.IntegerField(default=0, verbose_name='attack')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='name')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('crew', models.CharField(choices=[('halley', 'Halley'), ('bopp', 'Bopp')], default='halley', max_length=6, verbose_name='crew')),
                ('is_admin', models.BooleanField(default=False, help_text='Designa se o usuário pode acessar este site de administração.', verbose_name='admin status')),
                ('is_active', models.BooleanField(default=True, help_text='Designa se este usuário deve ser tratado como ativo. Desmarque isso em vez de excluir contas.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='auth_user_groups', to='auth.group', verbose_name='auth.User.groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='auth_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.attribute', verbose_name='attributes')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-id'],
            },
        ),
    ]
