# Generated by Django 5.0.7 on 2024-08-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attack',
            field=models.IntegerField(default=1, verbose_name='attack'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='life',
            field=models.IntegerField(default=1, verbose_name='life'),
        ),
        migrations.AlterField(
            model_name='user',
            name='attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attributes', to='users.attribute', verbose_name='attributes'),
        ),
    ]
