# Generated by Django 5.0.7 on 2024-08-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_attribute_attack_alter_attribute_life_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.attribute', verbose_name='attributes'),
        ),
    ]
