# Generated by Django 5.0.7 on 2024-08-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='life',
            field=models.IntegerField(default=3, verbose_name='life'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='PointsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='Points Distributed')),
                ('life_points', models.PositiveIntegerField(verbose_name='Life Points')),
                ('attack_points', models.PositiveIntegerField(verbose_name='Attack Points')),
                ('distributed_at', models.DateTimeField(auto_now_add=True, verbose_name='Distributed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_distributions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'points distribution',
                'verbose_name_plural': 'points distributions',
            },
        ),
        migrations.CreateModel(
            name='UserStatusRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_won', models.PositiveIntegerField(default=0, verbose_name='Games Won')),
                ('ranking', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ranking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_ranking', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user status ranking',
                'verbose_name_plural': 'user status rankings',
            },
        ),
    ]
