# Generated by Django 5.0.7 on 2024-08-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_attribute_life_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsdistribution',
            name='points',
        ),
    ]
