# Generated by Django 5.0.7 on 2024-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_pointsdistribution_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsdistribution',
            name='attack_points',
            field=models.IntegerField(verbose_name='Attack Points'),
        ),
        migrations.AlterField(
            model_name='pointsdistribution',
            name='life_points',
            field=models.IntegerField(verbose_name='Life Points'),
        ),
    ]
