# Generated by Django 5.0.7 on 2024-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pointsdistribution_attack_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsdistribution',
            name='attack_points',
            field=models.IntegerField(default=0, verbose_name='Attack Points'),
        ),
        migrations.AlterField(
            model_name='pointsdistribution',
            name='life_points',
            field=models.IntegerField(default=0, verbose_name='Life Points'),
        ),
    ]
