# Generated by Django 5.0.7 on 2024-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_pointsdistribution_attack_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_distributed_points',
            field=models.IntegerField(default=0, verbose_name='Total Distributed Points'),
        ),
    ]
