# Generated by Django 5.0.7 on 2024-08-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_total_distributed_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_distributed_points',
            new_name='distributed_points',
        ),
    ]
