# Generated by Django 5.0.7 on 2024-09-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_total_distributed_points_user_distributed_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attributes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.attribute', verbose_name='attributes'),
        ),
    ]
