# Generated by Django 5.0.7 on 2024-09-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.attribute', verbose_name='attributes'),
        ),
    ]
