# Generated by Django 5.0.7 on 2024-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crew',
            field=models.CharField(choices=[('halley', 'Halley'), ('bopp', 'Bopp')], default='halley', max_length=6, null=True, verbose_name='crew'),
        ),
    ]
