# Generated by Django 5.0.7 on 2024-08-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='image',
            field=models.ImageField(default='galaxies/galaxyTest.jpg', upload_to='galaxies/', verbose_name='Galaxy'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
