# Generated by Django 5.0.7 on 2024-08-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planets', '0006_alter_question_hint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Iniciado'), ('F', 'Finalizado'), ('W', 'Vitória'), ('L', 'Derrota')], default='S', max_length=1, verbose_name='Status')),
                ('user_life', models.PositiveIntegerField(default=3, verbose_name='User Life')),
                ('user_attack', models.PositiveIntegerField(default=1, verbose_name='User Attack')),
                ('creature_life', models.PositiveIntegerField(default=10, verbose_name='Creature Life')),
                ('creature_attack', models.PositiveIntegerField(default=1, verbose_name='Creature Attack')),
                ('points_awarded', models.PositiveIntegerField(default=3, verbose_name='Points Awarded')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='planets.creature', verbose_name='Creature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='End Time')),
                ('points_awarded', models.PositiveIntegerField(default=3, verbose_name='Points Awarded')),
                ('victory_image', models.URLField(blank=True, null=True, verbose_name='Victory Image')),
                ('defeat_image', models.URLField(blank=True, null=True, verbose_name='Defeat Image')),
                ('victory_message', models.TextField(blank=True, null=True, verbose_name='Victory Message')),
                ('defeat_message', models.TextField(blank=True, null=True, verbose_name='Defeat Message')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='game.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_correctly', models.BooleanField(default=False, verbose_name='Answered Correctly')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='game.game', verbose_name='Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='planets.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'game question',
                'verbose_name_plural': 'game questions',
            },
        ),
    ]
