# Generated by Django 5.0.7 on 2024-08-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='points_awarded',
        ),
    ]
