# Generated by Django 5.0.7 on 2024-08-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_points_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creature',
        ),
    ]
