# Generated by Django 5.0.7 on 2024-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_creature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_attack',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_life',
        ),
    ]
