# Generated by Django 5.0.7 on 2024-08-26 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_user_attack_remove_game_user_life'),
        ('planets', '0007_alter_creature_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameend',
            name='defeat_image',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='defeat_message',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='victory_image',
        ),
        migrations.RemoveField(
            model_name='gameend',
            name='victory_message',
        ),
        migrations.AddField(
            model_name='gameend',
            name='lost_creatures',
            field=models.ManyToManyField(blank=True, to='planets.creature'),
        ),
        migrations.AddField(
            model_name='gameend',
            name='points_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameend',
            name='questions_answered',
            field=models.ManyToManyField(blank=True, to='planets.question'),
        ),
        migrations.AddField(
            model_name='gameend',
            name='result',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='gameend',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameend',
            name='total_wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameend',
            name='user',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
